### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by lex**

### CODE REVIEW

**Comment by srautiai** [comment]
Atte, can you list here the new folder structure/tree. Pullo request is massive and it's hard to say what's changed

**Comment by lex** [comment]
The best way is probably to view it from here: https://github.com/lex/bitbar-samples/tree/refactor

**Comment by srautiai** [comment]
```.
├── appium
│   ├── sample-scripts
│   │   ├── csharp
│   │   │   └── Test123
│   │   ├── java
│   │   │   └── src
│   │   │       └── test
│   │   │           ├── java
│   │   │           │   └── com
│   │   │           │       └── testdroid
│   │   │           │           └── appium
│   │   │           │               ├── android
│   │   │           │               │   └── sample
│   │   │           │               └── ios
│   │   │           │                   └── sample
│   │   │           └── resources
│   │   ├── javascript
│   │   │   └── nightwatch_web_example
│   │   │       ├── build
│   │   │       └── tests
│   │   │           └── reports
│   │   ├── python
│   │   └── ruby
│   │       └── parallel-test
│   │           └── spec
│   └── server-side
│       ├── python
│       └── ruby
├── apps
│   ├── android
│   │   ├── BitbarSampleApp
│   │   │   ├── app
│   │   │   │   └── src
│   │   │   │       └── main
│   │   │   │           ├── java
│   │   │   │           │   └── com
│   │   │   │           │       └── bitbar
│   │   │   │           │           └── testdroid
│   │   │   │           └── res
│   │   │   │               ├── drawable
│   │   │   │               ├── drawable-hdpi
│   │   │   │               ├── drawable-ldpi
│   │   │   │               ├── drawable-mdpi
│   │   │   │               ├── drawable-xhdpi
│   │   │   │               ├── layout
│   │   │   │               └── values
│   │   │   └── gradle
│   │   │       └── wrapper
│   │   └── TestdroidSample
│   │       ├── gradle
│   │       │   └── wrapper
│   │       └── testdroidSample
│   │           └── src
│   │               ├── debug
│   │               └── main
│   │                   ├── assets
│   │                   │   └── www
│   │                   │       └── res
│   │                   ├── java
│   │                   │   ├── com
│   │                   │   │   └── testdroid
│   │                   │   │       └── sample
│   │                   │   │           └── android
│   │                   │   │               ├── adapters
│   │                   │   │               ├── game
│   │                   │   │               ├── models
│   │                   │   │               └── services
│   │                   │   └── utils
│   │                   └── res
│   │                       ├── anim
│   │                       ├── drawable
│   │                       ├── drawable-hdpi
│   │                       ├── drawable-xhdpi
│   │                       ├── drawable-xxhdpi
│   │                       ├── layout
│   │                       ├── layout-land
│   │                       ├── menu
│   │                       ├── raw
│   │                       └── values
│   └── builds
├── calabash
│   ├── BitbarSampleAppTest
│   │   └── features
│   │       ├── step_definitions
│   │       └── support
│   ├── TestdroidStepsParsingSkeleton
│   │   ├── config
│   │   └── features
│   │       ├── step_definitions
│   │       └── support
│   │           └── patches
│   └── TestdroidTest
│       ├── config
│       └── features
│           ├── step_definitions
│           └── support
├── detox
│   └── sample-react-native-bitbar
│       ├── android
│       │   ├── app
│       │   │   ├── build
│       │   │   │   └── outputs
│       │   │   │       └── apk
│       │   │   │           ├── androidTest
│       │   │   │           │   └── release
│       │   │   │           └── release
│       │   │   └── src
│       │   │       ├── androidTest
│       │   │       │   └── java
│       │   │       │       └── com
│       │   │       │           └── sampleproject
│       │   │       └── main
│       │   │           ├── java
│       │   │           │   └── com
│       │   │           │       └── sampleproject
│       │   │           └── res
│       │   │               ├── mipmap-hdpi
│       │   │               ├── mipmap-mdpi
│       │   │               ├── mipmap-xhdpi
│       │   │               ├── mipmap-xxhdpi
│       │   │               └── values
│       │   ├── gradle
│       │   │   └── wrapper
│       │   └── keystores
│       ├── e2e
│       ├── images
│       └── ios
│           ├── SampleProject
│           │   ├── Base.lproj
│           │   └── Images.xcassets
│           │       └── AppIcon.appiconset
│           ├── SampleProject-tvOS
│           ├── SampleProject-tvOSTests
│           ├── SampleProject.xcodeproj
│           │   └── xcshareddata
│           │       └── xcschemes
│           ├── SampleProjectTests
│           └── build
│               └── Build
│                   └── Products
│                       └── Release-iphonesimulator
│                           └── sampleproject.app
│                               ├── Base.lproj
│                               ├── Frameworks
│                               │   ├── IDEBundleInjection.framework
│                               │   │   └── _CodeSignature
│                               │   └── XCTest.framework
│                               │       ├── _CodeSignature
│                               │       └── en.lproj
│                               ├── PlugIns
│                               │   ├── sampleprojectTests.xctest
│                               │   │   └── _CodeSignature
│                               │   └── sampleprojectTests.xctest.dSYM
│                               │       └── Contents
│                               │           └── Resources
│                               │               └── DWARF
│                               ├── _CodeSignature
│                               └── assets
│                                   └── images
├── docker
│   └── jenkins
├── espresso-sample
│   └── BitbarSampleApp
│       ├── app
│       │   └── src
│       │       ├── androidTest
│       │       │   └── java
│       │       │       └── com
│       │       │           └── bitbar
│       │       │               └── testdroid
│       │       │                   └── sampletests
│       │       └── main
│       │           ├── java
│       │           │   └── com
│       │           │       └── bitbar
│       │           │           └── testdroid
│       │           └── res
│       │               ├── drawable
│       │               ├── drawable-hdpi
│       │               ├── drawable-ldpi
│       │               ├── drawable-mdpi
│       │               ├── drawable-xhdpi
│       │               ├── layout
│       │               └── values
│       └── gradle
│           └── wrapper
├── image-recognition
│   ├── lib
│   │   ├── linux
│   │   │   └── akaze
│   │   ├── mac
│   │   │   └── akaze
│   │   └── win
│   │       └── akaze
│   ├── queryimages
│   └── src
│       ├── main
│       │   └── java
│       └── test
│           └── java
├── ios
│   └── ios-test-skeleton
│       ├── ext
│       │   └── jasmine
│       │       ├── lib
│       │       │   └── jasmine-1.2.0
│       │       ├── spec
│       │       └── src
│       ├── reporters
│       └── specs
├── robot-framework
│   ├── libs
│   ├── resources
│   │   └── app
│   ├── tests-android
│   └── tests-ios
├── self-play-tests
│   └── appium
│       └── python
├── testdroid-cloud
│   └── examples
│       └── ruby
└── xcode
    ├── calculator
    │   ├── Assets.xcassets
    │   │   └── AppIcon.appiconset
    │   └── Base.lproj
    ├── calculator.xcodeproj
    │   └── project.xcworkspace
    ├── calculatorTests
    ├── calculatorUITests
    ├── ipa
    └── tests
```

**Comment by srautiai** [comment]
https://github.com/bitbar/testdroid-samples is copy of the current bitbar-samples repo(without history) - There is links out there pointing to this repo so those links will work and can be updated to bitbar-samples later

**Pull request merged**
